spring.application.name=springdemo
server.port = 8080

spring.datasource.url = JDBC:mysql://${MYSQL_HOST:localhost}:3306/library
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.key = ksjgisdigjijsdigjisddskddksfko0sovgag46wsnxbk084yssj
jwt.expiration-time = 10000000